.vscode/settings.json
vscode 꿀팁: customLabels로 직관적으로 파일을 보기
https://code.visualstudio.com/docs/getstarted/userinterface#_customize-tab-labels
이게 뭔지 알기 어려움
편안~
=> inv-62 vscode customLabels 부착

.github/workflows/deploy-preview.yaml, src/app/page.tsx
=> inv-27 배포 프리뷰 comment 테스트

.vscode/tasks.json, package.json
사용법(맥):
command + shift + p -> Tasks:Run Task -> 원하는 task 실행
자주 사용하는 task 등록해두면 편하게 사용할 수 있어요!
=> chore: tasks.json을 추가합니다.

src/components/editor/elements/container.tsx, src/components/editor/elements/map-placeholder.tsx, src/components/editor/elements/map-share.tsx, src/components/editor/elements/recursive.tsx, src/components/editor/sidebar-components-tab.tsx, src/components/editor/sidebar-settings-tab.tsx, src/components/editor/type.ts
=> INV-68 주소 블럭 컴포넌트

src/app/(auth)/sign-in/google/callback/route.ts, src/app/(auth)/sign-in/kakao/callback/route.ts, src/app/(auth)/sign-in/naver/callback/route.ts, src/app/(auth)/sign-out/actions.ts, src/app/(auth)/sign-out/route.ts, src/app/(playground)/pg/invitation-response/[responseId]/page.tsx, src/app/(playground)/pg/invitation-response/invitation-response-list.tsx, src/app/(playground)/pg/test/[testId]/page.tsx, src/app/(playground)/pg/test/test-list.tsx, src/lib/db/schema/test.query.ts
=> fix: rename from playground to pg

src/lib/db/schema/invitations.query.ts
커스텀 url 기반 중복 여부 조회 로직을 구현했습니다.
=> Feature/inv-120 커스텀 url 기반 중복 여부 조회 로직 구현

src/lib/db/schema/templates.query.ts
초대장 템플릿 CRUD 메서드를 구현했습니다.
- 목록 조회
- 단건 조회 (id)
- 생성
- 수정
- 삭제
=> Feature/inv 122 템플릿 CRUD 메서드 구현

src/lib/db/schema/users.query.ts
회원 탈퇴 및 로그아웃 메서드를 구현했습니다.
회원 탈퇴 로직의 경우 추루 템플릿 / 초대장 기능 개발 완료 후 cascade delete 구현이 필요합니다.
=> Feature/inv-108 회원 탈퇴 및 로그아웃 구현

src/app/(playground)/pg/editor/page.tsx, src/app/(playground)/pg/page.tsx, src/components/editor/action.ts, src/components/editor/constant.ts, src/components/editor/elements/element-helper.tsx, src/components/editor/elements/text.tsx, src/components/editor/index.tsx, src/components/editor/main.tsx, src/components/editor/navigation.tsx, src/components/editor/provider.tsx, src/components/editor/title-input.tsx, src/components/editor/type.ts
에디터에 수정에 대한 필요한 데이터를 세팅할 수 있도록 했습니다.
엘리먼트 리스트를 쉽게 다루기 위해서 `editor.elements` → `editorData`로 구분했습니다.
=> feat: editor 설정

src/lib/db/schema/invitations.query.ts
=> [inv-114] feat: 초대장 생성 API

src/lib/db/schema/invitations.query.ts, src/lib/db/schema/invitations.ts, src/lib/db/schema/templates.query.ts
- 초대장 단건 조회
- 초대장 리스트 조회
- 유저 초대장 리스트 조회
=> [inv-115] feat: 초대장 단건/리스트 조회 API

src/components/editor/action.ts, src/components/editor/elements/element-helper.tsx, src/components/editor/sidebar-element-settings-tab/background-setting.tsx, src/components/editor/sidebar-element-settings-tab/index.tsx, src/components/editor/sidebar-element-settings-tab/layout-setting.tsx, src/components/editor/sidebar-element-settings-tab/text-setting.tsx, src/components/editor/ui/input.tsx
선택된 엘리먼트의 상태가 변경되지 않는 현상을 대응했습니다.
추가로 에디터 input에 debounce를 적용했습니다.
=> fix: 선택된 엘리먼트의 상태가 변경되지 않는 현상

src/lib/db/schema/invitations.query.ts, src/lib/db/schema/templates.query.ts
=> [inv-117] feat: 초대장 삭제 API

src/app/(main)/dashboard/page.tsx, src/app/(main)/i/[subdomain]/edit/page.tsx, src/app/(playground)/pg/[subdomain]/page.tsx
=> INV-128: 대시보드 > 초대장 > 리스트 연동 

src/lib/db/schema/invitations.query.ts, src/lib/db/schema/invitations.ts
- eventDate, description 필드 제거
- eventUrl notNull 추가
=> fix: invitation schema

src/components/editor/elements/container.tsx, src/components/editor/elements/kakao-map-element.tsx, src/components/editor/placeholders.tsx, src/components/editor/sidebar-elements-tab.tsx
불피요한 코드를 제거했어요.
이미지 추가시 맵도 추가되는 현상 고쳤어요.
=> refactor: cleanup

src/components/editor/elements/blank-element.tsx, src/components/editor/elements/container.tsx, src/components/editor/elements/recursive.tsx, src/components/editor/placeholders.tsx, src/components/editor/sidebar-element-settings-tab/index.tsx, src/components/editor/sidebar-elements-tab.tsx, src/components/editor/type.ts
=> inv-92 inv-94 엘리먼트 > 여백

src/lib/db/schema/invitations.query.ts
=> Revert "feat: user id 사용 로직 쿠키로 대체"

src/components/editor/action.ts, src/components/editor/constant.ts, src/components/editor/navigation.tsx, src/components/editor/provider.tsx, src/components/editor/sidebar-settings-tab.tsx, src/components/editor/title-input.tsx, src/components/editor/type.ts, src/components/editor/ui/input.tsx
설정 마크업을 적용했습니다.
`editorConfig`를 `editor.config`로 적용되도록 했습니다.
=> inv-76 사이드바 > 사이트 설정 > 마크업

src/lib/db/schema/invitations.ts, src/lib/db/schema/templates.ts
invitation, template table `thumbnail_url` field 추가
=> [inv-145] feat: thumbnailUrl field 추가

src/components/editor/elements/container.tsx, src/components/editor/elements/kakao-map.tsx, src/components/editor/elements/navigation-element.tsx, src/components/editor/elements/recursive.tsx, src/components/editor/placeholders.tsx, src/components/editor/sidebar-element-settings-tab/index.tsx, src/components/editor/sidebar-element-settings-tab/map-setting.tsx, src/components/editor/sidebar-elements-tab.tsx, src/components/editor/type.ts
길찾기 navigation 엘리먼트를 리팩토링했습니다.
=> refactor: map find > navigation

src/app/(main)/dashboard/template-item.tsx, src/app/(main)/i/[subdomain]/page.tsx, src/app/layout.tsx, src/components/editor/sidebar/sidebar-settings-tab.tsx, src/lib/db/schema/invitations.query.ts
=> feat: OG 이미지 설정

src/components/editor/navigation.tsx, src/components/gloabl-loading.tsx
=> feat: 초대장 복제하기 기능

src/components/editor/elements/accordion-element.tsx, src/components/editor/elements/container.tsx, src/components/editor/type.ts
accordion element에 container가 들어갈 수 있도록 했습니다.
=> refactor: accordion element innerContainer

src/components/editor/action.ts, src/components/editor/constant.ts, src/components/editor/navigation.tsx, src/components/editor/sidebar/index.tsx, src/components/ui/tooltip-simple.tsx
=> feat: editor tooltip 

src/app/(main)/i/[subdomain]/page.tsx, src/app/(playground)/pg/bottom-sheet/_components/bottom-sheet/index.tsx, src/components/editor/action.ts, src/components/editor/fab/image-radio/container.tsx, src/components/editor/fab/image-radio/index.tsx, src/components/editor/fab/image-radio/option.tsx, src/components/editor/fab/index.tsx, src/components/editor/fab/invitation-response-fab.tsx, src/components/editor/main.tsx, src/components/editor/sidebar/sidebar-invitation-response-tab.tsx
참여여부 바텀시트 스타일링 / 사이드탭에서 사용 여부 수정 가능
=> inv-151: 참여여부 바텀시트

src/components/editor/action.ts, src/components/editor/provider.tsx
=> fix: editor history

src/app/(main)/dashboard/page.tsx, src/components/editor/navigation.tsx, src/components/profile-dropdown.tsx, src/components/providers.tsx, src/components/theme-dropdown.tsx
=> feat: darkmode

src/lib/db/schema/invitation_response.query.ts
get 함수 invitation_id 기반으로 변경하였습니다
=> fix: invitation_id 기반 get
